#!/bin/bash
CONTAINER=$(cmd/container-name);
FPM='_phpfpm';
CONTAINER_FPM=$CONTAINER$FPM;

docker stop $(docker ps -a | grep "$CONTAINER" | cut -d' ' -f1)

cd .dev/docker || exit

docker exec -it --user $(id -u):$(id -g) $CONTAINER_FPM composer install