version: '3.8'
services:

  phpfpm:
    build:
      dockerfile: ./phpfpm/Dockerfile
      context: .
      target: dev_phpfpm
    container_name: ${COMPOSE_PROJECT_NAME}_phpfpm
    volumes:
      - ../..:/var/www/html
      - ~/.composer/cache:/home/local/.composer/cache

